[package]
name = "rustybears"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.9", features = ["json"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
thousands = "0.2.0"
tokio = { version = "1.42.0", features = ["full"] } 
